// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function GetAnnouncements() {
  return window['go']['main']['App']['GetAnnouncements']();
}

export function GetKnowledge() {
  return window['go']['main']['App']['GetKnowledge']();
}

export function GetLogs() {
  return window['go']['main']['App']['GetLogs']();
}

export function GetSettings() {
  return window['go']['main']['App']['GetSettings']();
}

export function ResetKnowledgeTemplate() {
  return window['go']['main']['App']['ResetKnowledgeTemplate']();
}

export function SaveAnnouncements(arg1) {
  return window['go']['main']['App']['SaveAnnouncements'](arg1);
}

export function SaveKnowledge(arg1) {
  return window['go']['main']['App']['SaveKnowledge'](arg1);
}

export function SaveSettings(arg1) {
  return window['go']['main']['App']['SaveSettings'](arg1);
}

export function StartBot() {
  return window['go']['main']['App']['StartBot']();
}

export function StopBot() {
  return window['go']['main']['App']['StopBot']();
}
