// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {main} from '../models';

export function GetLogs():Promise<Array<string>>;

export function GetSettings():Promise<main.ControlSettings>;

export function SaveSettings(arg1:main.ControlSettings):Promise<void>;

export function StartBot():Promise<void>;

export function StopBot():Promise<void>;
